### ISSUE TITLE
资源合并冲突

### ISSUE THREAD

**Issue by wxw-9527** [pili-engineering/QNDroidWhiteBoardSDK#16]
`W:\.gradle\caches\transforms-2\files-2.1\4385c215e7a1ea1fecf985a3302fda5e\qndroid-whiteboard-1.1.5\res\values\values.xml:2:4: Duplicate value for resource 'attr/scaleType' with config 'DEFAULT' and product ''. Resource was previously defined here: W:\.gradle\caches\transforms-2\files-2.1\0ababd6a32d6e0d49681da6b78ed1d0a\camera-view-1.0.0-alpha30\res\values\values.xml:6:4: .`

请问有解决方案么？

**Comment by MJLblabla** [comment]
试一试最新版本

**Comment by wxw-9527** [comment]
优秀，最新版本已经可以了
